"""table added

Revision ID: c7c4f75c8e4f
Revises: 
Create Date: 2025-11-13 09:09:42.272987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7c4f75c8e4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kindergartens', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('kindergartens', sa.Column('phone_number', sa.String(length=255), nullable=False))
    op.add_column('kindergartens', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('kindergartens', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('kindergartens', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('kindergartens', sa.Column('age_limit', sa.String(length=255), nullable=False))
    op.add_column('kindergartens', sa.Column('islaw', sa.Boolean(), nullable=False))
    op.add_column('kindergartens', sa.Column('mini_gallery', sa.JSON(), nullable=False))
    op.alter_column('kindergartens', 'type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('kindergartens', 'type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('kindergartens', 'mini_gallery')
    op.drop_column('kindergartens', 'islaw')
    op.drop_column('kindergartens', 'age_limit')
    op.drop_column('kindergartens', 'end_time')
    op.drop_column('kindergartens', 'start_time')
    op.drop_column('kindergartens', 'capacity')
    op.drop_column('kindergartens', 'phone_number')
    op.drop_column('kindergartens', 'location')
    # ### end Alembic commands ###
